import ts from 'typescript';import fs from 'node:fs';import assert from 'node:assert/strict';
const js=ts.transpileModule(fs.readFileSync(new URL('../lib/transfer.ts',import.meta.url),'utf8'),{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ES2022}}).outputText;
const {Transfer,digest,frameChunk}=await import('data:text/javascript;base64,'+Buffer.from(js).toString('base64'));
function harness(){const sent=[];const channel={readyState:'open',bufferedAmount:0,send:x=>sent.push(x)};const t=new Transfer(channel,{state:()=>{},offer:()=>{},done:()=>{},trust:()=>{}});t.trusted=t.remoteTrusted=true;return {t,sent,channel};}
function slowFile(){let resolve;return {file:{name:'slow.txt',type:'text/plain',size:3,arrayBuffer:()=>new Promise(r=>{resolve=r;})},release:()=>resolve(new Uint8Array([1,2,3]).buffer)};}
const results=[];async function test(name,fn){try{await fn();results.push({name,status:'passed'});}catch(e){results.push({name,status:'failed',error:e.message});}}
await test('cancel_while_reading_does_not_send_offer',async()=>{const {t,sent}=harness(),s=slowFile();const task=t.offer(s.file);t.cancel();s.release();await task;assert.equal(sent.length,0);assert.equal(t.outgoing,null);});
await test('concurrent_offer_is_reserved_before_read',async()=>{const {t}=harness(),s=slowFile();const first=t.offer(s.file);await assert.rejects(t.offer(new File(['x'],'second.txt')),/等待/);s.release();await first;});
await test('duplicate_accept_does_not_send_bytes_twice',async()=>{const {t,sent}=harness();await t.offer(new File(['abc'],'x.txt'));const id=t.outgoing.meta.id;await t.receive(JSON.stringify({kind:'accept',id}));await t.receive(JSON.stringify({kind:'accept',id}));assert.equal(sent.filter(x=>typeof x!=='string').length,1);});
await test('ack_before_send_cannot_claim_success',async()=>{const {t}=harness();await t.offer(new File(['abc'],'x.txt'));const {id,sha}=t.outgoing.meta;await t.receive(JSON.stringify({kind:'ack',id,sha}));assert.notEqual(t.outgoing,null);});
await test('channel_failure_during_read_does_not_send_offer',async()=>{const {t,sent}=harness(),s=slowFile();const task=t.offer(s.file);t.fail('lost');s.release();await task;assert.equal(sent.length,0);assert.equal(t.outgoing,null);});
await test('receiver_double_accept_emits_one_accept',async()=>{const {t,sent}=harness();const b=new Uint8Array([1]).buffer;const meta={kind:'offer',id:crypto.randomUUID(),name:'r1',type:'',size:1,sha:await digest(b)};await t.receive(JSON.stringify(meta));t.accept();t.accept();assert.equal(sent.filter(x=>typeof x==='string'&&JSON.parse(x).kind==='accept').length,1);});
await test('duplicate_end_emits_one_verified_ack',async()=>{const {t,sent}=harness();const b=new Uint8Array([1]).buffer;const meta={kind:'offer',id:crypto.randomUUID(),name:'r2',type:'',size:1,sha:await digest(b)};await t.receive(JSON.stringify(meta));t.accept();await t.receive(frameChunk(meta.id,0,b));await Promise.all([t.receive(JSON.stringify({kind:'end',id:meta.id})),t.receive(JSON.stringify({kind:'end',id:meta.id}))]);assert.equal(sent.filter(x=>typeof x==='string'&&JSON.parse(x).kind==='ack').length,1);});
console.log(JSON.stringify({kind:'Deterministic protocol race regressions; mocked channel, not RTC transport',results},null,2));if(results.some(r=>r.status!=='passed'))process.exitCode=1;
